Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,4 +54,7 @@ jobs:
 
      
       - name: Deploy Subdirectory to Heroku
-        run: git subtree push  -f --prefix webapp/backend heroku main
+        run: |
+          git fetch heroku main || echo "No remote to fetch"
+
+          git subtree push --prefix webapp/backend heroku main || echo "Deployment failed"
